### PR TITLE
Update openapi-generator to v5.3.0

### PR DESCRIPTION
**Pull request by wing328**
Update openapi-generator to v5.2.1

cc @jrouly @jimschubert

### CODE REVIEW

**Comment by tovbinm** [comment]
can we please get this merged?

**Comment by tovbinm** [comment]
`5.3.0` is out - https://github.com/OpenAPITools/openapi-generator/releases

**Comment by jrouly** [comment]
So sorry for the delay. I need to run CI again and see why this is failing, then I can merge.

**Comment by tovbinm** [comment]
Thank you!!

**Comment by jrouly** [comment]
CI looks good. I went ahead and bumped to 5.3.0 as well.

**Comment by tovbinm** [comment]
Thank you! When is it going to be released?

**Comment by jrouly** [comment]
Unfortunately because of https://github.com/OpenAPITools/sbt-openapi-generator/issues/35 we're currently not able to release the plugin publicly.

**Pull request merged**
