### PR TITLE
Upgrade to 5.0.0-beta3

### PR DESCRIPTION
**Pull request by jrouly**
Just upgrades to the recently released `5.0.0-beta3`.

### CODE REVIEW

**Comment by jrouly** [comment]
cc @jimschubert

**Comment by jimschubert** [comment]
These beta suffixes don't work with the versioning in the plugin release. We'd either need to fix that first, or stick with snapshots until the full 5.0.0 release.

**Comment by jrouly** [comment]
@jimschubert Got it. I just saw https://github.com/OpenAPITools/sbt-openapi-generator/issues/5 as well. If the bintray repo supports snapshots (looks like it does?) I'm totally happy to work with snapshots. Unfortunately the versioning in this repo is static so they're not getting published on merges.

I'm not sure if you're open to it, but I'd be happy to set up [`sbt-dynver`](https://github.com/dwijnand/sbt-dynver) for versioning instead, which would handle snapshots and versioning a little more automatically - you'd just need to create tagged releases for the repo on Github.

**Comment by jrouly** [comment]
This also explains why I wasn't able to write a scripted test for my last PR adding the new SBT key - the version being submitted to the scripted test was the incorrect static version from `master` rather than the snapshot being built. I can submit a PR for that too now.

**Pull request closed without merging**
