### PR TITLE
v7.7.0 release

### PR DESCRIPTION
**Pull request by wing328**

### CODE REVIEW

**Comment by turboFei** [comment]
Hi @wing328 
Excuse me, I tried to use sbt-openapi-generator 7.7.0, but seems it was not released. 
```
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          org.openapitools:sbt-openapi-generator:7.7.0 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.openapitools:sbt-openapi-generator;sbtVersion=1.0;scalaVersion=2.12:7.7.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/fwang12/.ivy2/localorg.openapitools/sbt-openapi-generator/scala_2.12/sbt_1.0/7.7.0/ivys/ivy.xml
[error]   not found: /dev/null/org/openapitools/sbt-openapi-generator_2.12_1.0/7.7.0/sbt-openapi-generator-7.7.0.pom
[error]   not found: https://maven-central.storage-download.googleapis.com/repos/central/data/org/openapitools/sbt-openapi-generator_2.12_1.0/7.7.0/sbt-openapi-generator-7.7.0.pom
[error]   not found: https://repo1.maven.org/maven2/org/openapitools/sbt-openapi-generator_2.12_1.0/7.7.0/sbt-openapi-generator-7.7.0.pom
[error]   not found: https://dl.bintray.com/typesafe/sbt-plugins/org.openapitools/sbt-openapi-generator/scala_2.12/sbt_1.0/7.7.0/ivys/ivy.xml
[error]   not found: https://dl.bintray.com/spark-packages/maven/org/openapitools/sbt-openapi-generator_2.12_1.0/7.7.0/sbt-openapi-generator-7.7.0.pom
[error]   not found: https://repository.apache.org/content/repositories/staging/org/openapitools/sbt-openapi-generator_2.12_1.0/7.7.0/sbt-openapi-generator-7.7.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.openapitools/sbt-openapi-generator/7.7.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.openapitools/sbt-openapi-generator/7.7.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.openapitools/sbt-openapi-generator/scala_2.12/sbt_1.0/7.7.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/releases/org/openapitools/sbt-openapi-generator_2.12_1.0/7.7.0/sbt-openapi-generator-7.7.0.pom
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:60)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:134)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:74)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:147)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:147)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:128)
[error]         at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:220)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:161)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3799)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error]         at sbt.Execute.work(Execute.scala:292)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error]         at java.base/java.lang.Thread.run(Thread.java:840)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.openapitools:sbt-openapi-generator;sbtVersion=1.0;scalaVersion=2.12:7.7.0

```

**Comment by wing328** [comment]
thanks for reporting the issue

just re-publish again. let's see how that goes

**Comment by wing328** [comment]
https://central.sonatype.com/artifact/org.openapitools/sbt-openapi-generator

updated to v7.7.0

**Comment by turboFei** [comment]
thanks @wing328  a lot, it works.

**Pull request merged**
